# config.py

RIG_DIR_DEFAULT       = r"C:\Data\Rig post 3-10-2026"
WATERCAL_DIR_DEFAULT  = r"C:\Data\Water-cal-2026"
SPOTCHECK_DIR_DEFAULT = r"C:\Data\SpotCheck"

OK_MARGIN = 10.0
STRIKE_MARGIN = 15.0

DAYS_FILTER_DEFAULT = 365